/* ---------------------------------------------------------------------------
 * pdfTranslator/configWriter.ts - Generate config files for pdf2zh_next
 *
 * Produces two files consumed by aidea_bridge.py:
 *   1. config.toml - pdf2zh_next translation engine configuration
 *   2. task.json   - bridge script parameters
 * -------------------------------------------------------------------------*/

import type { BridgeTask } from "./types";

/**
 * Generate a config.toml string for pdf2zh_next with openaicompatible service.
 *
 * Only the openaicompatible service is enabled; all others are disabled.
 * The OAuth access_token is passed as openai_compatible_api_key.
 */
export function generateConfigToml(params: {
  model: string;
  apiKey: string;
  apiUrl: string;
  sourceLang: string;
  targetLang: string;
  qps: number;
  noDual: boolean;
  noMono: boolean;
  disableRichTextTranslate?: boolean;
  enhanceCompatibility?: boolean;
  translateTableText?: boolean;
  fontFamily?: "auto" | "serif" | "sans-serif" | "script";
  ocr?: boolean;
  autoOcr?: boolean;
  saveGlossary?: boolean;
  disableGlossary?: boolean;
  dualMode?: "LR" | "TB";
  transFirst?: boolean;
  skipClean?: boolean;
  noWatermark?: boolean;
  customSystemPrompt?: string;
  enableJsonModeIfRequested?: boolean;
  ignoreCache?: boolean;
}): string {
  // TOML doesn't have a standard JS library in Zotero/Gecko,
  // so we build the string manually. This is safe because all
  // values are numbers, booleans, or controlled strings.
  const esc = (s: string) =>
    s
      .replace(/\\/g, "\\\\")
      .replace(/"/g, '\\"')
      // eslint-disable-next-line no-control-regex -- escapes TOML backspace
      .replace(/\u0008/g, "\\b")
      .replace(/\t/g, "\\t")
      .replace(/\n/g, "\\n")
      .replace(/\f/g, "\\f")
      .replace(/\r/g, "\\r")
      .replace(
        // eslint-disable-next-line no-control-regex -- escapes remaining TOML controls
        /[\u0000-\u0007\u000B\u000E-\u001F\u007F]/g,
        (ch) => `\\u${ch.charCodeAt(0).toString(16).padStart(4, "0")}`,
      );

  const fontFamily =
    params.fontFamily && params.fontFamily !== "auto"
      ? `"${esc(params.fontFamily)}"`
      : `"null"`; // pdf2zh_next interprets "null" as auto-detect
  const customPrompt =
    params.customSystemPrompt && params.customSystemPrompt.trim()
      ? `"${esc(params.customSystemPrompt)}"`
      : `"null"`;
  const noWatermark = params.noWatermark !== false;

  return `# Auto-generated by AIdea plugin - do not edit
openaicompatible = true

[translation]
lang_in = "${esc(params.sourceLang)}"
lang_out = "${esc(params.targetLang)}"
qps = ${params.qps}
ignore_cache = ${params.ignoreCache === true}
custom_system_prompt = ${customPrompt}
save_auto_extracted_glossary = ${params.saveGlossary === true}
no_auto_extract_glossary = ${params.disableGlossary === true}
primary_font_family = ${fontFamily}

[pdf]
no_dual = ${params.noDual}
no_mono = ${params.noMono}
watermark_output_mode = "${noWatermark ? "no_watermark" : "watermarked"}"
use_alternating_pages_dual = ${params.dualMode === "TB"}
dual_translate_first = ${params.transFirst === true}
skip_clean = ${params.skipClean === true}
disable_rich_text_translate = ${params.disableRichTextTranslate === true}
enhance_compatibility = ${params.enhanceCompatibility === true}
translate_table_text = ${params.translateTableText === true}
ocr_workaround = ${params.ocr === true}
auto_enable_ocr_workaround = ${params.autoOcr === true}
only_include_translated_page = false

[openaicompatible_detail]
translate_engine_type = "OpenAICompatible"
support_llm = "yes"
openai_compatible_model = "${esc(params.model)}"
openai_compatible_base_url = "${esc(params.apiUrl)}"
openai_compatible_api_key = "${esc(params.apiKey)}"
openai_compatible_timeout = "300"
openai_compatible_enable_json_mode = ${params.enableJsonModeIfRequested === true}
`;
}

/**
 * Generate the task.json string for aidea_bridge.py.
 */
export function generateTaskJson(task: BridgeTask): string {
  return JSON.stringify(task, null, 2);
}
